"""empty message

Revision ID: 1aba699734a
Revises: None
Create Date: 2015-06-13 09:44:20.351834

"""

# revision identifiers, used by Alembic.
revision = '1aba699734a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
